file_info:
  file_type: json
  expected_rows: null
  encoding: utf-8
  delimiter: ','
  has_header: true
  json_schema:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
        format: email
    required:
    - id
    - name
    - email
  json_root_path: null
  jsonl_array_mode: false
columns:
- name: id
  type: integer
  required: true
  range:
    min: 1
    max: 999999
- name: name
  type: string
  required: true
  length:
    min: 1
    max: 100
- name: email
  type: email
  required: true
- name: age
  type: integer
  required: false
  range:
    min: 0
    max: 120
- name: address
  type: object
  required: false
- name: tags
  type: array
  required: false
