file_info:
  file_type: csv
  expected_rows: null
  encoding: utf-8
  delimiter: ','
  has_header: true
columns:
- name: 번호
  type: datetime
  required: true
  format: '%Y-%m-%d %H:%M:%S'
- name: '구분

    (증권/보험)'
  type: string
  required: true
  length:
    min: 2
    max: 2
- name: 질문구성 유형
  type: string
  required: true
  length:
    min: 8
    max: 13
  allowed_values:
  - 상품비교 추천형
  - 투자성향 및 조건 기반형
  - 고객 특성 강조형
  case_sensitive: false
- name: 질의자 성별
  type: string
  required: true
  length:
    min: 2
    max: 2
  allowed_values:
  - 남성
  - 여성
  case_sensitive: false
- name: 질의자 나이
  type: datetime
  required: true
  format: '%Y-%m-%d %H:%M:%S'
- name: 질문
  type: string
  required: true
  length:
    min: 78
    max: 184
  allowed_values:
  - 저는 40대 남성으로 현재 주식형 펀드를 보유하고 있습니다. 펀드 투자 경험이 있으며, 앞으로 5년 동안 투자할 계획입니다. 환매가 가능한
    상품을 선호하며, 미국 주식형 펀드와 중국 주식형 펀드 중  최근 1년 수익률을 비교하여 어떤 상품이 더 적합할지 추천해 주세요.
  - '40대 중반이고 단기 고수익을 목표로 합니다.

    1억 원을 1년 동안 투자할 계획인데, 미국 기술주 중심의 레버리지 상품도 고려하고 있습니다.

    적합한 상품이 있을까요?'
  - 현재 은행 예금을 보유 중인 50대 초반 여성입니다. 큰 손실 없이 원금을 지키면서 예금보다는 조금 더 나은 수익을 얻고 싶습니다. 국내 채권
    위주의 안정적인 이자 수익 추구 상품과 주식이 일부 포함된 혼합형 상품 중 어떤 것이 저에게 더 적합한지 추천해 주실 수 있을까요?
  - 결혼 앞두고 있는 30대 여성인데, 안정추구형이라서 결혼 준비 자금을 3년 동안 안전하게 불리고 싶어. 적합한 금융 상품 추천해줄 수 있어?
  - 은퇴를 앞두고 있는 60대 초반 남성인데, 예금은 조금 있지만 은퇴 후 생활 안정이 제일 중요해. 매월 생활비를 보충해줄 수 있는 금융 상품
    추천해줄 수 있어?
  - 주식이나 펀드에 투자했던 경험이 있는 60대 중반 남성입니다. 최근 몇 년간은 투자 활동이 없었고, 이제 자녀들도 다 키워 생활 안정을 도모해야
    할 시점입니다. 장기적으로 운용할 수 있는 적합한 금융 상품이 뭐가 있을까요? 추천 부탁드립니다.
  - 지금까지 적금이랑 CMA만 했는데, 최근 국내 ETF에 소액으로 투자해본 30대 남자야. 앞으로는 국내 코스닥 시장에도 꾸준히 적립식으로 투자하면서
    성장성 높은 곳에 참여하고 싶어. 원금 손실은 감수할 수 있고, 장기적으로 자산 불리기에 관심 많아. 적극투자형 성향인데, 어떤 투자 방법이
    적합할까?
  - 20대 후반 남성입니다. 첫 직장에 입사한 지 1년이 되었으며, 현재 자산은 많지 않지만 장기적으로 자산을 증대시키고 싶습니다. ETF 적립식
    투자와 해외 주식형 펀드 중 어떤 투자 방식이 저에게 더 적합할지 추천 부탁드립니다.
  - 30대 남자인데, ETF랑 TDF 중에 뭐가 더 유리한지 궁금해요. 글로벌 주식형 ETF는 이미 갖고 있는데, 은퇴 준비 때문에 TDF도 고민
    중이라서요. 수익률, 수수료, 유동성, 세제 혜택 측면에서 ETF와 TDF의 차이 좀 알려주세요.
  - 요즘 연금 계좌에 관심을 가지게 된 50대 여성이에요. 사실 은행 예금과 배당주 ETF로 안정적인 투자를 해왔는데, 이제 좀 더 다양한 투자를
    해보려고요. 타깃데이트펀드와 배당 ETF를 놓고 고민 중인데, 수수료가 어떤지, 세제 혜택은 뭐가 더 좋은지 비교 좀 해주세요. 안정적인 수익을
    추구하는 저에게는 어떤 게 더 유리할까요?
  case_sensitive: false
- name: COT1
  type: string
  required: true
  length:
    min: 58
    max: 288
  allowed_values:
  - '고객특성 분석:

    - 고객은 현재 주식형 펀드를 보유하고 있어 적극적 투자성향 임을 알 수 있습니다

    - 미국과 중국의 주식형 펀드 중 최근 1년의 실적 수익률이 더 높은 상품을 추천받고 싶어 합니다 '
  - '  고객은 단기 고수익을 목표로 하며, 레버리지 상품까지 고려하고 있으므로, 공격적 투자형에 해당합니다.'
  - 50대 초반 여성이라는 점에서, 일반적으로 안정적인 자산 관리와 노후 대비를 위한 금융 상품에 대한 관심이 높을 것으로 예상됩니다. 이 연령대는
    은퇴가 가까워짐에 따라 자산 증식도 중요하지만, 원금 손실 위험을 최소화하는 것이 더욱 중요한 시기입니다. 따라서, 투자 성향은 안정성과 수익성을
    동시에 추구하는 경향이 있을 것입니다. 또한, 은행 예금을 보유하고 있다는 점에서 이미 어느 정도 보수적인 투자 성향을 가지고 있을 가능성이
    큽니다.
  - 결혼이 예정되어 있는 30대 여성 고객이라는 점에서, 결혼 준비 자금을 안정적으로 관리하고 싶은 요구가 있습니다. 이 연령대의 고객은 일반적으로
    결혼, 주택 마련 등 중요한 생애 이벤트를 앞두고 있어, 자산의 안전성과 예측 가능한 수익에 대한 관심이 높습니다. 또한, 3년이라는 비교적
    짧은 기간 동안 자금을 운용해야 하므로, 높은 위험보다는 낮은 위험을 선호할 가능성이 큽니다. 이러한 특성은 고객이 안정추구형 투자 성향을
    가지고 있다는 점과 일치합니다.
  - 60대 초반 남성이라는 점에서 은퇴 후 안정적인 생활을 가장 중요하게 생각하는 고객임을 알 수 있습니다. 이 연령대의 고객들은 일반적으로 자산을
    급격히 늘리기보다는, 보유하고 있는 자산을 안정적으로 관리하면서 매월 일정한 현금 흐름을 확보하는 것을 선호합니다. 또한, 예금이 조금 있지만
    추가적인 소득원이 필요하다는 점에서, 원금 보존과 함께 정기적인 수익 분배가 가능한 금융 상품을 찾고 있을 가능성이 높습니다.
  - 60대 중반 남성 고객이라는 점에서, 일반적으로 은퇴를 앞두고 있거나 이미 은퇴한 상태일 가능성이 높습니다. 이 연령대의 투자자는 안정적인
    현금 흐름과 자산의 보존을 중요하게 여기며, 높은 변동성을 가진 상품보다는 장기적으로 안정적인 수익을 추구할 가능성이 큽니다. 또한, 자녀
    양육이 마무리되어 생활 안정을 도모해야 하는 시점이라는 점에서, 향후 몇 년간의 생활비를 안정적으로 확보할 수 있는 금융 상품을 선호할 것으로
    보입니다.
  - 질문자는 30대 남성으로, 지금까지 적금과 CMA를 통해 비교적 안정적인 금융 상품을 이용해 왔으나 최근 국내 ETF에 소액 투자를 시작한
    경험이 있습니다. 이는 금융 상품에 대한 기본적인 이해가 있으며, 투자 경험이 조금씩 쌓여가고 있음을 의미합니다. 또한, 질문자는 원금 손실에
    대한 감수 의지가 있고, 장기적으로 자산을 불리려는 목표를 가지고 있습니다. 이러한 특성은 질문자가 단순히 안정적인 상품보다는 성장 가능성이
    높은 상품에 관심을 두고 있음을 나타냅니다.
  - 20대 후반의 남성으로 첫 직장에 입사한 지 1년이 된 고객은 이제 막 사회 초년생으로서의 삶을 시작한 단계입니다. 자산은 많지 않지만 장기적으로
    자산을 증대시키고자 하는 목표를 가지고 있습니다. 이는 일반적으로 안정적인 직장 생활을 통해 정기적인 수입이 있지만, 아직 큰 규모의 자산을
    보유하지 않은 사회 초년생의 전형적인 재무 상황을 반영합니다. 이 고객은 장기적인 관점에서 자산을 증식하고 싶어 하며, 이는 위험 감수 성향이
    상대적으로 낮거나, 혹은 장기적인 안정성을 중시하는 투자 성향을 나타낼 수 있습니다.
  - 질문하신 분은 30대 남성으로, 이미 글로벌 주식형 ETF를 보유하고 있으며 은퇴 준비를 위해 TDF(Target Date Fund)를 고려하고
    있습니다. 이는 장기적인 자산 증식과 은퇴 후 안정적인 현금 흐름을 목표로 하는 투자자로서, 투자 경험이 어느 정도 있으며 글로벌 주식형 ETF를
    통해 이미 주식 시장에 대한 이해도가 있다는 것을 의미합니다. 또한, 은퇴 준비를 염두에 두고 있어 노후 자금 마련과 관련된 상품에 관심이
    많고, 자산 배분의 자동 조절과 같은 TDF의 특징에 매력을 느낄 가능성이 높습니다.
  - 50대 여성 고객님께서는 안정적인 투자 경험을 가지고 있으며, 은행 예금과 배당주 ETF를 통해 투자 활동을 해오셨습니다. 이 연령대의 투자자는
    일반적으로 은퇴를 앞두고 있어, 자산 보호와 안정적인 수익 창출에 관심이 많을 것으로 판단됩니다. 또한, 다양한 투자 상품을 통해 포트폴리오를
    확장하려는 의지를 보이므로, 위험과 수익의 균형을 잘 맞춘 상품을 선호할 가능성이 높습니다.
  case_sensitive: false
- name: COT2
  type: string
  required: true
  length:
    min: 56
    max: 391
  allowed_values:
  - '고객특성에 맞는 상품군 비교:

    - 고객이 비교하려는 상품은 미국시장에 투자하는 펀드와 중국시장의 펀드입니다

    - 고객의 비교기준은 동일 위험의 상품중 수익률입니다. 현재 판매중인 미국펀드와 중국펀드의 1년 실적 수익률을 비교하면 중국펀드의 수익률이
    전반적으로 높습니다

    - 따라서 중국 펀드 중 고객의 투자성향에 부합하면서 수익률이 높은 상품이 고객에게 적합한 상품 인 것으로 판단됩니다'
  - 고객은 1억 원을 1년이라는 초단기 동안 운용하며, 미국 기술주 변동성을 활용한 고수익을 추구합니다.
  - 요구사항을 살펴보면, 큰 손실 없이 원금을 지키면서 예금보다는 조금 더 나은 수익을 얻고 싶다는 점이 핵심입니다. 이는 원금 보장과 더불어
    안정적인 이자 수익을 추구한다는 의미입니다. 또한, 국내 채권 위주의 안정적인 이자 수익 추구 상품과 주식이 일부 포함된 혼합형 상품 중 어떤
    것이 더 적합한지 묻고 있습니다. 이 두 가지 옵션은 각각 안정성과 수익성의 측면에서 차이가 있습니다. 채권 위주 상품은 원금 손실 위험이
    낮고 이자 수익이 안정적이지만, 주식 혼합형 상품은 주식 시장의 성과에 따라 더 높은 수익을 기대할 수 있는 반면, 그만큼 손실 위험도 존재합니다.
  - 고객의 요구사항을 분석해보면, 결혼 준비 자금을 3년 동안 안전하게 불리고 싶다는 점이 핵심입니다. 이는 원금 손실 위험을 최소화하면서도,
    인플레이션 이상의 수익을 기대할 수 있는 상품을 원한다는 의미입니다. 또한, 3년이라는 기간 동안 운용할 예정이므로, 해당 기간 동안 안정적인
    수익을 제공하는 상품이 필요합니다. 고객이 안정추구형이라는 점에서, 변동성이 낮고, 꾸준한 수익을 기대할 수 있는 투자 상품이 적합합니다.
    더불어, 고객이 결혼 준비로 인해 자금 유동성이 필요할 수 있으므로, 환매수수료 없이 자유롭게 자금을 인출할 수 있는 상품인지도 고려해야 합니다.
  - 고객이 원하는 주요 요구사항은 매월 생활비를 보충할 수 있는 안정적인 금융 상품입니다. 이는 매월 일정한 현금 흐름을 제공해야 하며, 원금
    보존에 대한 우려가 적어야 합니다. 또한, 중도환매 수수료가 없어 필요할 때 쉽게 현금화할 수 있는 유연성도 중요합니다. 위험등급은 낮은 위험
    수준으로 안정추구형 투자자에게 적합한 상품이 필요하며, 예금금리를 상회하는 수익률을 기대할 수 있는 상품이어야 합니다.
  - 고객은 주식이나 펀드에 투자했던 경험이 있지만, 최근 몇 년간 투자 활동이 없었습니다. 이는 아마도 시장의 변동성에 대한 부담이나, 다른 이유로
    인해 투자를 잠시 중단했을 가능성이 있습니다. 이제 다시 투자를 고려한다는 점에서, 과거의 투자 경험을 살려 어느 정도의 수익성을 기대하면서도,
    안정성을 중시할 것으로 판단됩니다. 또한, 장기적으로 운용할 수 있는 상품을 찾고 있다는 점에서, 단기적인 고수익보다는 장기적인 자산 증식과
    안정적인 수익 창출이 가능한 상품을 선호할 것입니다.
  - 질문자는 국내 코스닥 시장에 꾸준히 적립식으로 투자하면서 성장성이 높은 곳에 참여하고 싶어 합니다. 이는 코스닥 시장의 높은 성장 잠재력에
    주목하고 있으며, 적립식 투자를 통해 장기적으로 리스크를 분산하고 자산을 증대시키려는 전략을 가지고 있음을 의미합니다. 또한, 질문자는 적극투자형
    성향을 가지고 있다고 스스로 밝히고 있습니다. 이는 변동성이 크더라도 높은 수익률을 기대할 수 있는 고위험 고수익 상품에 적합하다는 것을 시사합니다.
    따라서, 질문자의 요구사항은 성장성 높은 국내 코스닥 시장에 대한 장기적이고 꾸준한 투자, 그리고 원금 손실의 가능성을 감수할 수 있는 적극투자형
    성향에 부합하는 상품을 찾는 것입니다.
  - 고객의 요구사항을 분석해보면, 첫 번째로 장기적인 자산 증대를 목표로 하고 있습니다. 이는 단기적인 수익보다는 시간이 지남에 따라 가치가 꾸준히
    증가할 수 있는 투자 방식을 선호한다는 의미입니다. 두 번째로, 현재 자산이 많지 않기 때문에 소액으로도 시작할 수 있는 투자 방식을 필요로
    합니다. 세 번째로, 사회 초년생으로서 직장 생활과 병행해야 하므로 투자 관리가 비교적 간편하고, 자동화된 방식으로 꾸준히 투자할 수 있는
    방법을 선호할 가능성이 높습니다. 이러한 요구사항을 종합해 볼 때, 적립식 투자 방식이 적합할 수 있습니다.
  - 투자자는 ETF와 TDF 중 어느 것이 더 유리한지를 수익률, 수수료, 유동성, 세제 혜택 측면에서 비교하고 싶어 합니다. ETF는 일반적으로
    낮은 수수료, 높은 유동성, 그리고 세제 혜택이 있다는 장점이 있습니다. 특히, 글로벌 주식형 ETF는 다양한 해외 주식에 분산 투자하여 높은
    수익률을 기대할 수 있고, 거래소에서 실시간으로 매매 가능하여 유동성이 뛰어납니다. 반면, TDF는 투자자의 은퇴 시점에 맞춰 자산 배분을
    자동으로 조절해주는 장점이 있습니다. 초기에는 주식 비중이 높아 수익률을 추구하다가, 은퇴 시점이 가까워질수록 채권 비중을 늘려 안정성을 강화하는
    전략을 취합니다. TDF는 연금저축계좌나 퇴직연금계좌를 통해 투자할 경우 세제 혜택이 더 크며, 장기 투자에 적합한 상품입니다.
  - 고객님께서는 타깃데이트펀드(TDF)와 배당 ETF 중 어떤 상품이 더 유리한지 고민 중입니다. 특히 수수료와 세제 혜택 측면에서 비교를 원하셨습니다.
    안정적인 수익을 추구하시는 만큼, 두 상품의 위험도와 수익 구조, 그리고 장기적인 투자 관점에서의 적합성을 고려해야 합니다. TDF는 목표
    시점에 맞춰 자산 배분이 자동으로 조절되는 장점이 있으며, 배당 ETF는 안정적인 배당 수익을 제공하는 특징이 있습니다.
  case_sensitive: false
- name: COT3
  type: string
  required: true
  length:
    min: 117
    max: 542
  allowed_values:
  - "적합상품 선택 및 선택사유:\n- 중국 펀드 중 DB차이나바이오헬스케어증권자투자신탁(UH)[주식]A-E를 추천합니다.\n- 해당 상품은 자산총액\
    \ 중 60% 이상을 중국, 홍콩, 미국 등에 상장된 중국대표 바이오헬스케어 기업에 투자한 모 펀드에 투자하는 상품으로 \n- 최근 1년 수익률이\
    \ 60%를 상회하고 있어 고수익 선호의 고객니즈에 부합하며, 위험등급은 높은위험(2등급)에 해당하나 적극적 투자형의 고객이 감내할 수 있는\
    \ 위험 수준입니다."
  - 고객의 목표에 가장 부합하는 상품은 미국 기술주 관련 레버리지 ETF입니다. 이는 공격적 투자형의 특성에 맞게 단기간에 높은 변동성을 활용하여
    수익을 극대화하려는 고객의 요구를 직접적으로 충족시키는 상품입니다.
  - 한화코리아밸류채권증권 자투자신탁(채권)은 국내 채권에 주로 투자하여 안정적인 이자 수익을 추구하는 상품입니다. 이 펀드는 A- 등급 이상의
    채권 및 A2- 등급 이상의 단기사채 등에 투자하며, 국채, 지방채, 특수채 등 다양한 채권으로 구성되어 있습니다. 또한, ESG 평가시스템을
    적용하여 사회적 책임 투자도 고려하고 있습니다. 위험등급은 5등급(낮은 위험)으로, 원금 손실 가능성이 매우 낮고, 예금보다는 높은 수익률을
    기대할 수 있습니다. 반면, 주식이 포함된 혼합형 상품은 상대적으로 높은 수익성을 제공할 수 있지만, 주식 시장의 변동성에 따라 원금 손실
    위험이 존재합니다. 따라서, 원금 보전을 최우선으로 하면서 안정적인 이자 수익을 원하는 요구사항과 가장 부합하는 상품은 한화코리아밸류채권증권
    자투자신탁(채권)입니다.
  - 흥국공모주로우볼채움플러스증권투자신탁1호는 고객의 요구사항에 부합하는 여러 특징을 가지고 있습니다. 첫째, 이 상품은 국내 우량채권에 주로 투자하여
    금리 변동 위험을 최소화합니다. 이는 원금 손실 위험을 줄이고, 안정적인 이자 수익을 확보할 수 있다는 점에서 안정추구형 고객에게 적합합니다.
    둘째, 로우볼(Low Volatility) 전략을 통해 변동성이 낮은 주식에도 일부 투자하여 추가적인 수익을 추구합니다. 이는 안정적인 채권
    투자와 함께, 시장 상황에 따라 적절한 수익을 기대할 수 있는 구조입니다. 셋째, 공모주 투자를 통해 추가적인 수익 기회를 제공합니다. 공모주는
    일반적으로 상장 초기 안정적인 수익을 기대할 수 있어, 3년 동안 자금을 운용하는 데 있어 플러스 요인이 될 수 있습니다. 마지막으로, 90일
    이상 보유 시 환매수수료가 없어, 결혼 준비 과정에서 필요할 때 자유롭게 자금을 인출할 수 있는 유동성을 제공합니다. 최근 1년 8.87%,
    3년 20.43%의 수익률은 고객의 3년 투자 기간 동안 안정적인 수익을 창출할 수 있는 가능성을 보여줍니다.
  - 이러한 요구사항을 충족하는 상품으로는 '미래에셋월지급식글로벌다이나믹증권자투자신탁1호(채권)(분배형)'가 적합합니다. 이 상품은 매월 분배금을
    현금으로 지급하도록 설계되어 있어, 은퇴 후 생활비 보충에 매우 유리합니다. 또한, 위험등급이 낮은 위험으로 안정추구형 투자자에게 적합하며,
    중도환매 수수료가 없어 유동성이 필요한 경우 즉시 현금화할 수 있습니다. 투자 전략은 미주, 유럽, 아시아 지역의 채권에 분산 투자하여 안정성을
    높였으며, 최근 1년 2.49%, 3년 7.81%의 수익률을 보여 예금금리를 상회하는 수익을 기대할 수 있습니다.
  - 이러한 요구사항을 충족시킬 수 있는 상품으로는 'KB밸류포커스30증권자투자신탁(채권혼합)A-E'가 적합해 보입니다. 이 상품은 채권과 주식을
    혼합하여 투자함으로써, 채권의 안정성과 주식의 성장성을 동시에 추구합니다. 자산총액의 50% 이상을 채권에 투자하여 안정성을 확보하고, 가치주에
    30%까지 투자하여 장기적으로 예금 금리 이상의 수익을 기대할 수 있습니다. 또한, 중도환매 수수료가 없어 필요할 때 현금화가 용이하고, 적립식
    투자가 가능한 추가형 상품구조로 장기적인 자산 운용에 적합합니다. 1년 11.06%, 3년 20.24%의 수익률은 장기적으로 안정적인 수익을
    제공할 가능성을 보여줍니다.
  - 이러한 요구사항을 충족하는 상품으로는 '미래에셋TIGER코스닥150증권상장지수투자신탁(주식)' ETF가 적합합니다. 이 ETF는 코스닥 150
    지수를 추종하여 국내 성장성 높은 코스닥 기업들에 분산 투자하는 구조를 가지고 있습니다. 적립식 투자가 가능하며, 중도 환매도 자유로워 질문자의
    투자 전략에 부합합니다. 또한, 위험등급이 1등급(매우 높은 위험)으로 분류되어 있어 적극투자형 성향을 가진 투자자에게 적합합니다. 과거 3년간
    수익률 변동성(97.5% VaR)이 59.87%로 높은 편이지만, 이는 코스닥 시장의 특성상 불가피한 부분입니다. 질문자는 이미 원금 손실의
    가능성을 감수할 수 있다고 언급했으므로, 이러한 변동성은 큰 문제가 되지 않을 것입니다.
  - 삼성KODEX 삼성전자채권혼합증권상장지수투자신탁[채권혼합]은 고객의 요구사항에 잘 부합하는 상품입니다. 이 상품은 삼성전자 주식과 국고채 Focus
    총수익 지수를 3:7 비중으로 분산 투자하여, 주식과 채권의 장점을 모두 활용합니다. 주식 비중을 30%로 제한함으로써, 상대적으로 안정적인
    채권 비중을 높여 위험을 관리합니다. 또한, 추가형 펀드로 적립식 투자가 가능해 소액으로도 꾸준히 투자할 수 있으며, 이는 고객의 현재 자산
    상황과 투자 목표에 부합합니다. 매월 수익분배를 통해 현금흐름을 제공하므로, 장기적으로 자산을 증대시키면서도 일정한 수익을 기대할 수 있습니다.
    위험등급은 보통위험으로, 사회 초년생이 감내할 수 있는 수준입니다.
  - 한화 LIFEPLUS TDF 2045 증권 투자신탁(혼합-재간접형)을 예로 들면, 이 상품은 2045년을 목표시점으로 하여 초기엔 주식 비중이
    높고, 시간이 지남에 따라 채권 비중을 늘리는 자산 배분 전략을 사용합니다. 이는 30대인 질문자님의 은퇴 시점(60세 전후)과 잘 맞아떨어질
    수 있습니다. 또한, 연금저축계좌나 퇴직연금계좌를 통해 가입하면 세제 혜택이 더 크다는 점에서 은퇴 준비와 세금 절감이라는 두 가지 목표를
    동시에 달성할 수 있습니다. 반면, ETF는 이미 보유하고 있으므로 추가적인 글로벌 주식형 ETF 투자보다는, 자산 배분 자동 조절과 세제
    혜택을 동시에 누릴 수 있는 TDF가 더 적합할 수 있습니다.
  - 한화 신종개인연금 TDF 2020은 2020년을 목표시점으로 설정하여 주식과 채권의 비중을 자동으로 조절합니다. 50대 여성 고객님과 같은
    은퇴를 앞둔 투자자에게 적합한 자산 배분 전략을 제공합니다. 이 펀드는 보통 위험 등급(4등급)으로, 안정적인 수익을 추구하면서도 어느 정도의
    성장 가능성을 제공합니다. 또한, 개인연금상품으로서 이자·배당소득세가 면제되고, 연간 72만원 범위 내에서 소득공제도 받을 수 있어 세제 혜택이
    큽니다. 반면, 배당 ETF는 일반적으로 주식 배당 수익에 초점을 맞추며, 수수료가 다양할 수 있고, 세제 혜택은 TDF에 비해 상대적으로
    제한적일 수 있습니다. 배당 ETF는 주식 시장의 변동성에 더 직접적으로 노출되므로, 안정성과 위험 관리 측면에서 TDF가 더 유리할 수 있습니다.
  case_sensitive: false
- name: Answer
  type: string
  required: true
  length:
    min: 30
    max: 430
  allowed_values:
  - DB차이나바이오헬스케어증권자투자신탁(UH)[주식]A-E
  - NH투자증권 - 재간접 - 글로벌 AI산업 증권자투자신탁(UH)[주식-재간접형]
  - 50대 초반 여성으로서 원금을 지키면서 예금보다 나은 수익을 추구하는 투자 성향을 고려할 때, 한화코리아밸류채권증권 자투자신탁(채권)을 추천드립니다.
    이 펀드는 국내 채권에 주로 투자하여 안정적인 이자 수익을 제공하며, 위험등급이 5등급(낮은 위험)으로 원금 손실 위험이 매우 낮습니다. 또한,
    ESG 평가시스템을 적용하여 사회적 책임 투자도 고려되므로, 장기적으로 안정적인 자산 관리에 적합합니다. 혼합형 상품은 더 높은 수익을 기대할
    수 있지만, 원금 손실 위험이 있으므로, 현재 요구사항에는 채권형 펀드가 더 적합합니다.
  - 결혼 준비 자금을 3년 동안 안전하게 불리고자 하는 30대 여성 고객님께 '흥국공모주로우볼채움플러스증권투자신탁1호'를 추천드립니다. 이 상품은
    국내 우량채권에 투자하여 금리 변동 위험을 최소화하며, 안정적인 이자 수익을 제공합니다. 또한, 로우볼 전략과 공모주 투자를 통해 추가적인
    수익 기회를 제공하여, 안정적이면서도 어느 정도의 수익성을 기대할 수 있습니다. 90일 이상 보유 시 환매수수료가 없어 결혼 준비 과정에서
    필요한 유동성을 확보할 수 있으며, 최근 3년 수익률이 20.43%로 고객님의 투자 기간 동안 안정적인 수익을 창출할 가능성이 높습니다.
  - 은퇴 후 생활 안정을 위해 매월 생활비를 보충할 수 있는 금융 상품을 찾으신다면, '미래에셋월지급식글로벌다이나믹증권자투자신탁1호(채권)(분배형)'를
    추천드립니다. 이 상품은 매월 분배금을 지급하여 안정적인 현금 흐름을 제공하며, 낮은 위험 등급으로 원금 보존에 대한 우려가 적습니다. 또한,
    중도환매 수수료가 없어 유동성이 필요할 때 쉽게 현금화할 수 있으며, 예금금리를 상회하는 수익률을 기대할 수 있어 은퇴 후 생활비 보충에 적합한
    상품입니다.
  - 고객님의 투자 경험과 현재 상황에 가장 적합한 금융 상품으로는 'KB밸류포커스30증권자투자신탁(채권혼합)A-E)'를 추천드립니다. 이 상품은
    채권과 주식을 혼합하여 투자함으로써, 안정성과 수익성을 동시에 추구할 수 있습니다. 특히, 50% 이상을 채권에 투자하여 안정성을 확보하고,
    국내 가치주에 30%까지 투자함으로써 장기적으로 예금 금리 이상의 수익을 기대할 수 있습니다. 또한, 중도환매 수수료가 없어 필요할 때 현금화가
    용이하고, 적립식 투자가 가능한 추가형 상품구조로 장기적인 자산 운용에 적합합니다. 1년 11.06%, 3년 20.24%의 수익률은 장기적으로
    안정적인 수익을 제공할 가능성을 보여주므로, 생활 안정을 도모하고 장기적으로 자산을 운용하고자 하는 고객님의 목표에 부합합니다.
  - 질문자의 성장성 높은 국내 코스닥 시장 투자, 장기 적립식 투자, 그리고 적극투자형 성향에 가장 적합한 상품은 '미래에셋TIGER코스닥150증권상장지수투자신탁(주식)'
    ETF입니다. 이 ETF는 코스닥 150 지수를 추종하며, 국내 성장성이 높은 코스닥 기업들에 분산 투자하는 구조로 설계되어 있습니다. 적립식
    투자가 가능하고, 중도 환매도 자유로우며, 위험등급이 1등급으로 적극투자형 투자자에게 적합합니다. 또한, 원금 손실의 가능성을 감수할 수 있는
    질문자의 투자 성향에 부합합니다. 장기적으로 자산을 불리려는 목표에 가장 잘 맞는 상품이라고 판단됩니다.
  - 삼성KODEX 삼성전자채권혼합증권상장지수투자신탁[채권혼합]을 추천드립니다. 이 상품은 삼성전자 주식과 국고채 Focus 총수익 지수를 3:7
    비중으로 분산 투자하여, 주식과 채권의 장점을 모두 활용하면서도 위험을 적절히 관리합니다. 또한, 적립식 투자가 가능해 소액으로도 꾸준히 투자할
    수 있으며, 매월 수익분배를 통해 장기적인 자산 증대와 함께 일정한 현금흐름을 제공합니다. 위험등급은 보통위험으로, 사회 초년생인 고객님의
    투자 성향에 적합합니다. 장기적으로 자산을 증대시키고 싶으신 고객님께 이 상품이 좋은 선택이 될 것입니다.
  - 30대 남성으로서 은퇴 준비를 위해 글로벌 주식형 ETF 외에 추가 투자를 고려하고 계신다면, 한화 LIFEPLUS TDF 2045 증권 투자신탁(혼합-재간접형)을
    추천드립니다. 이 TDF는 2045년을 목표시점으로 하여, 초기에는 주식 비중을 높게 유지하여 수익률을 추구하다가 은퇴 시점에 가까워질수록
    채권 비중을 늘려 안정성을 강화하는 전략을 취합니다. 이는 30대인 질문자님의 은퇴 시점(60세 전후)과 잘 맞아떨어질 수 있습니다. 또한,
    연금저축계좌나 퇴직연금계좌를 통해 가입할 경우 세제 혜택이 크며, 자산 배분을 자동으로 조절해주는 점에서 장기 투자 및 은퇴 준비에 매우 유리합니다.
    이미 글로벌 주식형 ETF를 보유하고 계신 상황에서, TDF는 추가적인 자산 배분 및 세제 혜택을 통해 포트폴리오의 안정성과 효율성을 높일
    수 있는 좋은 선택이 될 것입니다.
  - 안정적인 수익을 추구하시는 50대 여성 고객님께는 한화 신종개인연금 TDF 2020을 추천드립니다. 이 상품은 목표 시점에 맞춰 자산 배분이
    자동으로 조절되어 은퇴를 앞둔 투자자에게 적합하며, 보통 위험 등급으로 안정적인 수익과 성장 가능성을 동시에 제공합니다. 또한, 이자·배당소득세
    면제와 소득공제 등 세제 혜택이 풍부하여 장기적인 투자 관점에서 유리합니다. 배당 ETF도 안정적인 배당 수익을 제공하지만, TDF의 자동
    자산 배분 기능과 세제 혜택을 고려했을 때, 고객님의 투자 목표와 성향에 더 부합하는 선택이 될 것입니다.
  case_sensitive: false
- name: 작업대상 표기
  type: string
  required: true
  length:
    min: 3
    max: 3
- name: 라벨러명
  type: string
  required: true
  length:
    min: 3
    max: 3
- name: 소속
  type: string
  required: true
  length:
    min: 4
    max: 4
- name: 1차교차검수자
  type: string
  required: true
  length:
    min: 3
    max: 3
- name: 소속.1
  type: string
  required: true
  length:
    min: 4
    max: 4
- name: 검수 의견
  type: string
  required: true
  length:
    min: 83
    max: 84
  allowed_values:
  - 추천근거가 단순히 최근 1년 수익률로 판단되어 장기투자계획(5년)과의 정합성 부족, 중국 특정섹터에 편중된 고위험 상품 권유 대비 적합성 설명
    불충분
  - 고객은 레버리지 ETF를 직접적으로 고려했는데 제안상품은 일반 재간접 펀드로 이어져 고객요청과 논리적 연결성 부족, 변동성과 손실위험에 대한
    설명 부족
  case_sensitive: false
- name: 검수상태
  type: boolean
  required: true
