file_info:
  expected_rows: 11 # 타이틀 행을 포함한 총 행 수
  encoding: "utf-8"
  delimiter: ","
  has_header: true

columns:
  - name: "id"
    type: "integer"
    required: true
    range:
      min: 1
      max: 100

  - name: "name"
    type: "string"
    required: true
    length:
      min: 2
      max: 20

  - name: "email"
    type: "email"
    required: true

  - name: "age"
    type: "integer"
    required: true
    range:
      min: 18
      max: 65

  - name: "department"
    type: "string"
    required: true
    allowed_values: ["개발팀", "마케팅팀", "영업팀", "인사팀"]
    case_sensitive: false
