file_info:
  expected_rows: 11 # 타이틀 행을 포함한 총 행 수
  encoding: "utf-8"
  delimiter: ","
  has_header: true

columns:
  - name: "student_id"
    type: "string"
    required: true
    pattern: "^2023\\d{3}$"

  - name: "student_name"
    type: "string"
    required: true
    length:
      min: 2
      max: 20

  - name: "math_score"
    type: "integer"
    required: true
    range:
      min: 0
      max: 100

  - name: "english_score"
    type: "integer"
    required: true
    range:
      min: 0
      max: 100

  - name: "science_score"
    type: "integer"
    required: true
    range:
      min: 0
      max: 100

  - name: "attendance_rate"
    type: "float"
    required: true
    range:
      min: 0.0
      max: 100.0

  - name: "grade_level"
    type: "integer"
    required: true
    range:
      min: 1
      max: 3
