file_info:
  file_type: json
  expected_rows: null
  encoding: utf-8
  delimiter: ","
  has_header: true
  json_schema:
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
      email:
        type: string
        format: email
      profile:
        type: object
      preferences:
        type: object
      created_at:
        type: string
      is_active:
        type: boolean
      tags:
        type: array
    required:
    - id
    - username
    - email
    - created_at
    - is_active
  json_root_path: null
  jsonl_array_mode: false

columns:
- name: id
  type: integer
  required: true
  range:
    min: 1
    max: 999999
- name: username
  type: string
  required: true
  length:
    min: 1
    max: 50
- name: email
  type: email
  required: true
- name: profile
  type: object
  required: true
- name: preferences
  type: object
  required: true
- name: created_at
  type: datetime
  required: true
  format: "%Y-%m-%d %H:%M:%S"
- name: is_active
  type: boolean
  required: true
- name: tags
  type: array
  required: true
